mongo:
  image: mongo
  ports:
    - 27017:27017
fluent:
  build: ./fluent
  ports:
    - 24224:24224
  links:
    - mongo
#  volumes:
#    - /data:/fluentd/log
#    - /root/docker/etc:/fluentd/etc
#  environment:
#    - FLUENTD_CONF=test2.conf
nginx:
  image: nginx:1.9
  ports:
    - 80:80
  log_driver: fluentd
  log_opt:
    fluentd-address: 192.168.1.12:24224
  links:
    - fluent
